### PR TITLE
Text edits first round

### PR DESCRIPTION
**Pull request by vhellstein**
@1000camels Darcy, these are just some initial text edits that I know would have been distracting as we finalize the design bits.

### CODE REVIEW

**Comment by 1000camels** [comment]
short_title corresponds to what is in the navbar for previous and next links
toc_title is what appears in the side TOC menu and on the Contents page
I assume you would want that to say "Essay" and then include the contributor name?

**Review by 1000camels — APPROVED** [review]

**Review by 1000camels — APPROVED** [review]

**Comment by vhellstein** [comment]
I'd rather not have "Essay" on the ToC/Contents page--either the full title or no title and just the author's name.

**Comment by 1000camels** [comment]
Ok, I was following the keynote and the conversation we had with Einor

**Comment by 1000camels** [comment]
Screen Shot 2023-02-09 at 9 51 10 AM
Normally the contributor is appended. Do you want that?

**Comment by vhellstein** [comment]
I think that looks great! Thanks!

**Pull request merged**
